### PR TITLE
Inclusion request for my own gem repo

### PR DESCRIPTION
**Pull request by jmarrec**
Added https://github.com/jmarrec/openstudio-effibem-measures-gem to manifest.json

It doesn't contain much yet, but I'm trying out the process, and have more things to migrate when I can carve out more time.

For now it has one measure that demonstrates how to create a ModelMeasure that acts like a ReportingMeasure except that you can "Apply Now" (without running the model)

### CODE REVIEW

**Review by kflemin — APPROVED** [review]

**Comment by kflemin** [comment]
@jmarrec, as soon as this is merged to the main branch, this repo will be added to the BCL.  Any release you make *after* you configure the webhook as described in step3 of this page: https://bcl2.nrel.gov/contribute will be added to the BCL automatically.  You can check the status of the releases on the dashboard page.  Let me know if you have any questions.  I am planning to merge this to the main branch in the next couple of days.

**Comment by jmarrec** [comment]
@kflemin Thanks. I added the webhook then created a release. I'll check the dashboard to ensure it worked.

**Comment by jmarrec** [comment]
@kflemin 4 hours later I still don't see it on the dashboard. Is there a way to check if the webhook actually worked somewhere?

**Comment by kflemin** [comment]
@jmarrec it will only work after the repo is added to the BCL, which will happen after your branch is merged to the main branch (which it hasn't been yet)...sorry for the confusion. Should be in the next couple of days!

**Comment by jmarrec** [comment]
will I need to actually redo a Release on my repo at that point or will it index it automatically?

**Comment by kflemin** [comment]
@jmarrec, yes you would have to redo the release. BCL only picks up the "release published" webhook when you click the publish button.   But this time I added it for you manually...you should be all set: https://bcl2.nrel.gov/repos/a342368a-0043-11ec-b0a2-129880bd8b7d

**Comment by jmarrec** [comment]
@kflemin thanks a lot!

**Pull request merged**
